spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/petclinic
    username: petclinic
    password: qKqUu2vAuf
    driverClassName: com.p6spy.engine.spy.P6SpyDriver

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: "UTC"
          lob:
            non_contextual_creation: true
    open-in-view: false
  flyway:
    locations: ["classpath:db/migration/ddl", "classpath:db/migration/dml"]

security:
  token:
    secret-key: "0d11efb73eb826d09403a0f0"
    expiration-time-seconds: 3600
    token-prefix: "Bearer"